apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
  labels:
    app: reddit-app
spec:
  replicas: 1 # Start with one replica
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app-container
        image: us-west2-docker.pkg.dev/mlops-456918/reddit-app-repo/redditapp:v1
        imagePullPolicy: Always
        command: ["/usr/local/bin/uvicorn"]
        args: ["redditApp:app", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8000 # Port the app listens on inside the container