# reddit-deployment-minikube.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
  labels:
    app: reddit-app
spec:
  replicas: 1 # Start with one replica
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app-container
        image: redditapp:v1 # Simple image name for local build
        imagePullPolicy: IfNotPresent # Or Never, since we build in Minikube
        ports:
        - containerPort: 8000 # Port the app listens on inside the container